# Site settings
title: Kiss Építők
email: kissfestes@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ide lehet írni kulcsszavakat
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kissfestes.hu" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
